### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by AntonLevchenko** [AntonLevchenko/homepage#6]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by volodymyr-kushnir** [comment]
@AntonLevchenko хей, привіт. Ти хочеш, щоб я тобі накопіпастив сюди чи зробиш сам? **Assignee** на мене стоїть, то я перепитую.

**Comment by AntonLevchenko** [comment]
Привіт. упс) ні, зроблю сам)

**Comment by volodymyr-kushnir** [comment]
@AntonLevchenko ну то як хочеш 😁, я піду тоді далі собі

**Comment by AntonLevchenko** [comment]
Hi, I’m a motivated  email/markup developer with 1+ years’ experience. I like to do web site and email templates and improve my skills every seconds, because it’s amazing. &#x1F929;
